name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: yarn
      - run: corepack enable

      - run: yarn
      - run: yarn dedupe --check

      - run: yarn lint
      - run: yarn build
